### ISSUE TITLE
External prober should be able to retrieve external probe binary from remote location (GCS/S3/etc)

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#25]
External prober should be able to retrieve external probe binary from remote location (GCS/S3/etc). This will allow for easy deployment of external probes.

**Comment by DazWilkin** [comment]
Having been initially drawn to deploying Cloudprober (as a container) on Kubernetes, I propose we consider a model in which external probes are (also) deployed as containers. For Kubernetes, this would then enable delivering external probes as sidecars but this approach appears to provide more general benefits: leveraging container registries for hosting external probes (rather than GCS|S3), unifying deployments and perhaps consider network (simple http) rather than stdout/pipe-based integration?

**Comment by manugarg** [comment]
Moved here: https://github.com/cloudprober/cloudprober/issues/27, as per https://github.com/google/cloudprober/discussions/679.
