### ISSUE TITLE
[QUESTION] HTTPS Certificate Expiration Metrics

### ISSUE THREAD

**Issue by jbkc85** [google/cloudprober#335]
Is there a way in the HTTP probe to pull down the delta on how much longer a given SSL certificate is valid for?  Blackbox Exporter in Prometheus provides this, but since we are using CloudProber already for HTTPS domain checks, I would like to keep it simple if possible.

I am searching through the docs - just can't find it yet! :-)

**Comment by manugarg** [comment]
@jbkc85 No, HTTP probe cannot do that yet. Since it's a very unique requirement, if we want to provide metric in HTTPS probe, we'd want to make it optional (enable through a config field for example).

I think the best option for you will be to create an external probe that will fetch and export this data. For example if you put the following in a script and run it through an external probe, you should get the desired result.

```
#!/bin/sh

target=${1}
expire_date=$(echo | openssl s_client -servername $target -connect $target:443 2>/dev/null | openssl x509 -noout -dates | grep notAfter | cut -d"=" -f2)
expire_epoch=$(date "+%s" -d "$expire_date")
echo "cert_expiration_time $expire_epoch"
```

External probe config:
```
probe {
  type: EXTERNAL
  name: "ssl_expiration_time"

  targets {
    host_names: "www.google.com,www.yahoo.com"
  }

  external_probe {
    command: "/tmp/x.sh @target@"
  }
}
```

It will produce metrics like this:
```
#TYPE probe_ssl_earliest_cert_expiry gauge
cert_expiration_time{ptype="external",probe="ssl_expiration_time",dst="www.google.com"} 1582642166.000 1576746316267
cert_expiration_time{ptype="external",probe="ssl_expiration_time",dst="www.yahoo.com"} 1582113600.000 1576746314517
```

**Comment by jbkc85** [comment]
seems easy enough.  Thanks for the tip!
