### ISSUE TITLE
Panic - configtest v0.10.8

### ISSUE THREAD

**Issue by dcloud9** [google/cloudprober#441]
We've upgraded from `v0.10.4` to `v0.10.8` and no breaking change apart from the `-configtest`. Panic output below
```
# /usr/local/bin/cloudprober -configtest -config_file=/etc/cloudprober/cloudprober.cfg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9cd2f6]
goroutine 1 [running]:
github.com/google/cloudprober/logger.(*Logger).Debugf(0x0, 0x12ebb99, 0x29, 0xc00063fab8, 0x1, 0x1)
        /home/runner/work/cloudprober/cloudprober/logger/logger.go:298 +0x26
github.com/google/cloudprober/sysvars.addGceNicInfo(0xc00002f9e0, 0x0)
        /home/runner/work/cloudprober/cloudprober/sysvars/sysvars_gce.go:145 +0x28c
github.com/google/cloudprober/sysvars.glob..func2(0xc00002f9e0, 0x0, 0x3, 0x1, 0x0)
        /home/runner/work/cloudprober/cloudprober/sysvars/sysvars_gce.go:87 +0x3c3
github.com/google/cloudprober/sysvars.initCloudMetadata(0x12c495f, 0x4, 0x12c92f3, 0x8)
        /home/runner/work/cloudprober/cloudprober/sysvars/sysvars.go:110 +0x240
github.com/google/cloudprober/sysvars.Init(0x0, 0xc00002f9b0, 0x0, 0x0)
        /home/runner/work/cloudprober/cloudprober/sysvars/sysvars.go:152 +0x28c
main.main()
        /home/runner/work/cloudprober/cloudprober/cmd/cloudprober.go:169 +0x377
```

**Comment by manugarg** [comment]
Much thanks for this bug report.

The problem seems to be here:
https://github.com/google/cloudprober/blob/2a846bd77287c913f68a6a67a8c828e03d2842c7/logger/logger.go#L298

Logger is always supposed to work even when uninitialized, but here we're checking for the debugLog property being set. This can be easily fixed.

(As an aside, I am kind of surprised why we haven't run into this issue yet internally. I'll continue to look into that.)

**Comment by manugarg** [comment]
> (As an aside, I am kind of surprised why we haven't run into this issue yet internally. I'll continue to look into that.)

I guess you're running this configtest on GCE, while we've never do that. Regardless, I'll get it fixed soon. We'll also release v0.10.9 in a couple of days.
