### ISSUE TITLE
abilility to log in json

### ISSUE THREAD

**Issue by melchiormoulin** [google/cloudprober#500]
Hello,
To set up a logging probe the logger need to output log in json. For now the logger seems not configurable for doing this.

**Comment by manugarg** [comment]
> To set up a logging probe the logger need to output log in json.

@melchiormoulin I don't follow this part. Can you please explain what you're trying to do.

**Comment by melchiormoulin** [comment]
The logging stack in my company in handling json format from the stdout of containers. To set up a logging probe we need to output cloudprober log in json.

**Comment by manugarg** [comment]
By logging probe, do you mean running a probe that verifies that logging is working?

Or, you want probe metrics to be logged in json format so that your existing logging infrastructure can use that data for monitoring (dashboards) and alerting purpose?

For the first option, you'll need to use an external probe: https://cloudprober.org/how-to/external-probe/.

and, for the second option, we'll need a json-logging surfacer: https://cloudprober.org/surfacers/overview/.

My point regarding #502 is that just exporting formatted string as json is not going to help any of the above two options a lot unless we change the whole source code to log differently.

Does that make sense?

**Comment by melchiormoulin** [comment]
I'm already currently developping the first option, my issue was more about to have  different kind of logs :

- in json  from my external probe
- in plain text from the cloudprober default logger

**Comment by manugarg** [comment]
@melchiormoulin I see. Adding json logger to cloudprober like this will not add any value other than consistency for your use case. It will unnecessarily increase cloudprober's dependencies and increase the binary size as 'zap' itself has a bunch of dependencies.
